# Generated by Django 4.2.4 on 2023-09-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveringCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('inn', models.CharField(max_length=150)),
                ('bank', models.CharField(max_length=150)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('mfo', models.IntegerField(blank=True, null=True)),
                ('xisob_raqam', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('delivery_name', models.CharField(max_length=150)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('delivered_date', models.DateField(auto_now_add=True)),
                ('region', models.CharField(max_length=150)),
                ('company_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivering_company', to='delivery.deliveringcompany')),
                ('product', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
