# Generated by Django 4.2.2 on 2023-09-16 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_rename_branch_brand_rename_branch_product_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveringCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('inn', models.CharField(max_length=150)),
                ('bank', models.CharField(max_length=150)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('mfo', models.IntegerField(blank=True, null=True)),
                ('xisob_raqam', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivering Companies',
            },
        ),
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('expenses', models.IntegerField(default=0)),
                ('delivered_date', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=150)),
                ('company_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivering_company', to='delivery.deliveringcompany')),
                ('product', models.ManyToManyField(blank=True, to='product.product')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
