# Generated by Django 3.2 on 2023-09-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveringcompany',
            options={'verbose_name_plural': 'Delivering Companies'},
        ),
    ]
