# Generated by Django 4.2.4 on 2023-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_branch_brand_rename_branch_product_brand_and_more'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivereditem',
            old_name='expenses',
            new_name='extra_cost',
        ),
        migrations.AlterField(
            model_name='delivereditem',
            name='product',
            field=models.ManyToManyField(related_name='delivered_product', to='product.product'),
        ),
    ]
