# Generated by Django 4.2.4 on 2023-09-06 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='branch',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'Tayyor'), ('being_prepared', 'Tayyorlanmoqda'), ('not_available', 'Mavjud emas')], max_length=50),
        ),
        migrations.DeleteModel(
            name='StatusProduct',
        ),
    ]
